# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Pull Request Checks

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven Settings
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Maven Distribution Server (step creates .m2/settings.xml)
          server-id: 'sonatype-central'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
